# via https://medium.com/@thakuravnish2313/setting-up-a-private-docker-registry-in-kubernetes-7c8f5f470cf8
# and https://k3s.rocks/private-registry/
# and http://ollama.lan:8080/c/63d366d8-2aa7-492f-bf1e-5cabf8e53c8d

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: docker.io/registry:3
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
      volumes:
      - name: registry-data
        #persistentVolumeClaim:
        #  claimName: registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  selector:
    app: registry
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP


# use ingress… or just the ports
# kubectl port-forward --address 0.0.0.0 svc/registry-service 5000
# curl registry-service.default.svc.cluster.local:5000/v2/_catalog  # only in cluster…
#
# kubectl describe svc registry-service
# kubectl run test-pod --image=busybox --rm -it -- /bin/sh
# wget -O - http://registry-service:5000/v2/_catalog
